[tool.black]
line-length = 88
target-version = ['py39']

[tool.flake8]
max-line-length = 88
extend-ignore = "E203,W503"
# E203: whitespace before ':' (conflicts with black)
# W503: line break before binary operator (black prefers this)
